name: golangci-lint
on:
  push:
    branches:
      - '**' # Run on all branches
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          go-version: '1.22'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: v1.57
          skip-cache: true
          args: --timeout=5m

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          go-version: '1.22'
      - name: Test all
        run: go test ./...